**Lab 2: Practice with Numpy**



***I. Vector***


Numpy (Numerical Python) - là một thư viện bao gồm các đối tượng mảng đa chiều (multidimentional array) và một tập hợp các phương thức để có thể xử lý mảng đó. Với numpy ta có thể sử dụng sụng các toán tử toán học, logic cùng các phương thức xử lý mảng để thực hiện trên đối tượng mục tiêu.
![numpy](https://i.imgur.com/mg8O3kd.png)

Một số ưu điểm của numpy:
- Chứa bộ các giá trị.
- Có thể chứa các kiểu dữ liệu khác nhau.
- Có thể thêm, xóa, sửa.
- Có đầy đủ chức năng tính toán.



Vector là một tuple của một hoặc nhiều giá trị vô hướng. Các vector được xây dựng từ các thành phần là các ordinary number (các kiểu int, float, ...). Có thể xem vector như một danh sách các số và đại số vector là các phép toán thực hiện trên các số bên trong danh sách đó.

Tên một vector là chữ thường - được ký hiệu như sau:
$$
  v = (x_1, x_2, x_3, ..., x_n)
$$
Trong đó:
- v là vector.
- $x_1, x_2, x_3, ..., x_n$ là các giá trị vô hướng

Một vector có thể được biểu diễn theo chiều ngang hoặc chiều dọc
$$
\begin{bmatrix}
   x_1 \\
   x_2 \\
   x_3 \\
   ... \\
   x_n
\end{bmatrix}
$$

In [24]:
import numpy as np

# Tạo vector ngẫu nhiên
v1 = np.random.randint(1, 10, 5)  # vector 5 phần tử
v2 = np.random.randint(1, 10, 5)

print("Vector v1:", v1)
print("Vector v2:", v2)



Vector v1: [8 7 9 9 8]
Vector v2: [2 3 2 9 5]


### Cộng hai vector
$$
c = a + b
$$
$$
c = (a_1+b_1, a_2+b_2, ..., a_n+b_n)
$$

In [25]:
# 1. Cộng vector
print("v1 + v2 =", v1 + v2)



v1 + v2 = [10 10 11 18 13]


### Trừ hai vector
$$
c = a - b
$$
$$
c = (a_1-b_1, a_2-b_2, ..., a_n-b_n)
$$

In [22]:
# 2. Trừ vector
print("v1 - v2 =", v1 - v2)



v1 - v2 = [-8  2  1  3  6]


# Nhân hai vector
$$
c = a * b
$$
$$
c = (a_1*b_1, a_2*b_2, ..., a_n*b_n)
$$

In [23]:


# 3. Nhân từng phần tử (Hadamard product)
print("v1 * v2 =", v1 * v2)

v1 * v2 = [ 9 48 72 28  7]


# Chia hai vector
$$
c = a / b
$$
$$
c = (a_1/b_1, a_2/b_2, ..., a_n/b_n)
$$

In [26]:
# 4. Chia từng phần tử
print("v1 / v2 =", v1 / v2)

v1 / v2 = [4.         2.33333333 4.5        1.         1.6       ]


In [ ]:

# 5. Nhân vô hướng
print("v1 . v2 =", np.dot(v1, v2))



# 6. Bình phương từng phần tử
print("v1^2 =", v1**2)

In [5]:
# 7. Nối 2 vector
print("Concat [v1, v2] =", np.concatenate((v1, v2)))




Concat [v1, v2] = [1 4 1 8 9 8 5 2 6 2]


In [6]:
# 8. Cắt 1 đoạn vector (slice)
print("v1[1:4] =", v1[1:4])

v1[1:4] = [4 1 8]


In [7]:
# 9. Lấy giá trị max/min
print("Max v1 =", np.max(v1), ", Min v1 =", np.min(v1))

Max v1 = 9 , Min v1 = 1


In [8]:
# 10. Sắp xếp vector
print("Sorted v1 =", np.sort(v1))

Sorted v1 = [1 1 4 8 9]


***II. Matrix***

In [10]:
# Tạo ma trận
A = np.random.randint(1, 10, (3, 3))
B = np.random.randint(1, 10, (3, 3))

print("Ma trận A:\n", A)
print("Ma trận B:\n", B)

Ma trận A:
 [[8 4 9]
 [3 1 4]
 [4 8 7]]
Ma trận B:
 [[9 1 1]
 [8 4 9]
 [3 2 8]]


In [11]:
# 1. Cộng ma trận
print("A + B =\n", A + B)

# 2. Trừ ma trận
print("A - B =\n", A - B)

# 3. Nhân từng phần tử
print("A * B =\n", A * B)

# 4. Tích ma trận (matrix multiplication)
print("A @ B =\n", A @ B)

# 5. Chuyển vị ma trận
print("A^T =\n", A.T)



A + B =
 [[17  5 10]
 [11  5 13]
 [ 7 10 15]]
A - B =
 [[-1  3  8]
 [-5 -3 -5]
 [ 1  6 -1]]
A * B =
 [[72  4  9]
 [24  4 36]
 [12 16 56]]
A @ B =
 [[131  42 116]
 [ 47  15  44]
 [121  50 132]]
A^T =
 [[8 3 4]
 [4 1 8]
 [9 4 7]]


In [12]:
# 6. Nối ma trận theo hàng
print("Nối theo hàng =\n", np.hstack((A, B)))

# 7. Nối ma trận theo cột
print("Nối theo cột =\n", np.vstack((A, B)))



Nối theo hàng =
 [[8 4 9 9 1 1]
 [3 1 4 8 4 9]
 [4 8 7 3 2 8]]
Nối theo cột =
 [[8 4 9]
 [3 1 4]
 [4 8 7]
 [9 1 1]
 [8 4 9]
 [3 2 8]]


In [13]:
# 8. Trích một dòng
print("Dòng 1 của A =", A[0])

# 9. Trích một cột
print("Cột 2 của A =", A[:, 1])

# 10. Cắt một khối con (sub-matrix)
print("Sub-matrix (2x2 từ A) =\n", A[:2, :2])



Dòng 1 của A = [8 4 9]
Cột 2 của A = [4 1 8]
Sub-matrix (2x2 từ A) =
 [[8 4]
 [3 1]]


In [14]:
# 11. Định thức ma trận
print("det(A) =", np.linalg.det(A))

# 12. Nghịch đảo ma trận (nếu khả nghịch)
try:
    print("A^-1 =\n", np.linalg.inv(A))
except np.linalg.LinAlgError:
    print("A không khả nghịch")


det(A) = -40.0
A^-1 =
 [[ 0.625 -1.1   -0.175]
 [ 0.125 -0.5    0.125]
 [-0.5    1.2    0.1  ]]


In [28]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [35]:
import os
print(os.getcwd())

/content


In [37]:
!mkdir -p "/content/drive/MyDrive/Python_sgu_2025_dophuthanh"


In [41]:
!mv /content/numpylab.ipynb "/content/drive/MyDrive/Python_sgu_2025_dophuthanh/"


mv: cannot stat '/content/numpylab.ipynb': No such file or directory
