**Lab 2: Practice with Numpy**



***I. Vector***


Numpy (Numerical Python) - là một thư viện bao gồm các đối tượng mảng đa chiều (multidimentional array) và một tập hợp các phương thức để có thể xử lý mảng đó. Với numpy ta có thể sử dụng sụng các toán tử toán học, logic cùng các phương thức xử lý mảng để thực hiện trên đối tượng mục tiêu.





Vector là một tuple của một hoặc nhiều giá trị vô hướng. Các vector được xây dựng từ các thành phần là các ordinary number (các kiểu int, float, ...). Có thể xem vector như một danh sách các số và đại số vector là các phép toán thực hiện trên các số bên trong danh sách đó.

Tên một vector là chữ thường - được ký hiệu như sau:
$$
  v = (x_1, x_2, x_3, ..., x_n)
$$
Trong đó:
- v là vector.
- $x_1, x_2, x_3, ..., x_n$ là các giá trị vô hướng

Một vector có thể được biểu diễn theo chiều ngang hoặc chiều dọc
$$
\begin{bmatrix}
   x_1 \\
   x_2 \\
   x_3 \\
   ... \\
   x_n
\end{bmatrix}
$$

In [1]:
import numpy as np

# Tạo vector ngẫu nhiên
v1 = np.random.randint(1, 10, 5)  # vector 5 phần tử
v2 = np.random.randint(1, 10, 5)

print("Vector v1:", v1)
print("Vector v2:", v2)



Vector v1: [8 3 4 7 1]
Vector v2: [5 3 2 6 7]


### Cộng hai vector
$$
c = a + b
$$
$$
c = (a_1+b_1, a_2+b_2, ..., a_n+b_n)
$$

In [3]:
# 1. Cộng vector
print("v1 + v2 =", v1 + v2)



v1 + v2 = [13  6  6 13  8]


### Trừ hai vector
$$
c = a - b
$$
$$
c = (a_1-b_1, a_2-b_2, ..., a_n-b_n)
$$

In [4]:
# 2. Trừ vector
print("v1 - v2 =", v1 - v2)



v1 - v2 = [ 3  0  2  1 -6]


# Nhân hai vector
$$
c = a * b
$$
$$
c = (a_1*b_1, a_2*b_2, ..., a_n*b_n)
$$

In [5]:


# 3. Nhân từng phần tử (Hadamard product)
print("v1 * v2 =", v1 * v2)

v1 * v2 = [40  9  8 42  7]


# Chia hai vector
$$
c = a / b
$$
$$
c = (a_1/b_1, a_2/b_2, ..., a_n/b_n)
$$

In [26]:
# 4. Chia từng phần tử
print("v1 / v2 =", v1 / v2)

v1 / v2 = [4.         2.33333333 4.5        1.         1.6       ]


In [6]:

# 5. Nhân vô hướng
print("v1 . v2 =", np.dot(v1, v2))



# 6. Bình phương từng phần tử
print("v1^2 =", v1**2)

v1 . v2 = 106
v1^2 = [64  9 16 49  1]


In [7]:
# 7. Nối 2 vector
print("Concat [v1, v2] =", np.concatenate((v1, v2)))




Concat [v1, v2] = [8 3 4 7 1 5 3 2 6 7]


In [8]:
# 8. Cắt 1 đoạn vector (slice)
print("v1[1:4] =", v1[1:4])

v1[1:4] = [3 4 7]


In [9]:
# 9. Lấy giá trị max/min
print("Max v1 =", np.max(v1), ", Min v1 =", np.min(v1))

Max v1 = 8 , Min v1 = 1


In [10]:
# 10. Sắp xếp vector
print("Sorted v1 =", np.sort(v1))

Sorted v1 = [1 3 4 7 8]



## II. Ma trận (Matrix)

### 1. Khái niệm
Ma trận là một mảng hai chiều (2D) gồm các số, được sắp xếp thành các hàng và cột. Trong NumPy, nó được biểu diễn bằng một `ndarray` có 2 chiều (ví dụ: `shape=(m, n)` với `m` hàng và `n` cột). Ma trận là nền tảng của đại số tuyến tính và được sử dụng rộng rãi trong khoa học dữ liệu và máy học.

Ký hiệu toán học của một ma trận `A` có `m` hàng và `n` cột:
$$
A = \begin{bmatrix}
   a_{11} & a_{12} & \cdots & a_{1n} \\
   a_{21} & a_{22} & \cdots & a_{2n} \\
   \vdots & \vdots & \ddots & \vdots \\
   a_{m1} & a_{m2} & \cdots & a_{mn}
\end{bmatrix}
$$

### 2. Các phép toán cơ bản
Các phép toán trên ma trận là trung tâm của nhiều thuật toán.

*   **Cộng/Trừ/Nhân từng phần tử (Element-wise):** Các phép toán này thực hiện trên từng cặp phần tử tương ứng của hai ma trận. Yêu cầu hai ma trận phải có cùng kích thước.
    *   `C = A + B`  => `c_ij = a_ij + b_ij`
*   **Tích ma trận (Matrix Multiplication):** Đây là phép toán cốt lõi trong đại số tuyến tính, khác với nhân từng phần tử. Tích của ma trận `A` (kích thước `m x n`) và `B` (kích thước `n x p`) sẽ là một ma trận `C` (kích thước `m x p`).
    *   Ký hiệu trong NumPy: `A @ B` hoặc `np.dot(A, B)`
    *   Công thức tính: `c_ij = \sum_{k=1}^{n} a_{ik} \cdot b_{kj}`
*   **Chuyển vị (Transpose):** "Lật" một ma trận qua đường chéo chính của nó, biến hàng thành cột và ngược lại.
    *   Ký hiệu: `A.T`
    *   Nếu `A` có shape `(m, n)` thì `A.T` sẽ có shape `(n, m)`.

### 3. Các hàm và khái niệm Đại số Tuyến tính
NumPy cung cấp module `linalg` để thực hiện các phép toán đại số tuyến tính phức tạp hơn.

*   **Định thức (Determinant - `np.linalg.det`):** Là một giá trị vô hướng đặc biệt có thể được tính từ một ma trận vuông. Định thức cho biết thông tin quan trọng về ma trận, ví dụ: nếu định thức bằng 0, ma trận không có nghịch đảo (singular matrix).
*   **Nghịch đảo (Inverse - `np.linalg.inv`):** Đối với một ma trận vuông `A`, ma trận nghịch đảo `A⁻¹` là ma trận mà khi nhân với `A` sẽ cho ra ma trận đơn vị `I`. Ma trận nghịch đảo chỉ tồn tại khi định thức của ma trận khác 0.
    $$
    A \cdot A^{-1} = A^{-1} \cdot A = I
    $$

In [11]:
# Tạo ma trận
A = np.random.randint(1, 10, (3, 3))
B = np.random.randint(1, 10, (3, 3))

print("Ma trận A:\n", A)
print("Ma trận B:\n", B)

Ma trận A:
 [[5 9 6]
 [4 1 5]
 [1 2 6]]
Ma trận B:
 [[5 4 6]
 [2 2 7]
 [7 3 9]]


In [12]:
# 1. Cộng ma trận
print("A + B =\n", A + B)

# 2. Trừ ma trận
print("A - B =\n", A - B)

# 3. Nhân từng phần tử
print("A * B =\n", A * B)

# 4. Tích ma trận (matrix multiplication)
print("A @ B =\n", A @ B)

# 5. Chuyển vị ma trận
print("A^T =\n", A.T)



A + B =
 [[10 13 12]
 [ 6  3 12]
 [ 8  5 15]]
A - B =
 [[ 0  5  0]
 [ 2 -1 -2]
 [-6 -1 -3]]
A * B =
 [[25 36 36]
 [ 8  2 35]
 [ 7  6 54]]
A @ B =
 [[ 85  56 147]
 [ 57  33  76]
 [ 51  26  74]]
A^T =
 [[5 4 1]
 [9 1 2]
 [6 5 6]]


In [13]:
# 6. Nối ma trận theo hàng
print("Nối theo hàng =\n", np.hstack((A, B)))

# 7. Nối ma trận theo cột
print("Nối theo cột =\n", np.vstack((A, B)))



Nối theo hàng =
 [[5 9 6 5 4 6]
 [4 1 5 2 2 7]
 [1 2 6 7 3 9]]
Nối theo cột =
 [[5 9 6]
 [4 1 5]
 [1 2 6]
 [5 4 6]
 [2 2 7]
 [7 3 9]]


In [14]:
# 8. Trích một dòng
print("Dòng 1 của A =", A[0])

# 9. Trích một cột
print("Cột 2 của A =", A[:, 1])

# 10. Cắt một khối con (sub-matrix)
print("Sub-matrix (2x2 từ A) =\n", A[:2, :2])



Dòng 1 của A = [5 9 6]
Cột 2 của A = [9 1 2]
Sub-matrix (2x2 từ A) =
 [[5 9]
 [4 1]]


In [15]:
# 11. Định thức ma trận
print("det(A) =", np.linalg.det(A))

# 12. Nghịch đảo ma trận (nếu khả nghịch)
try:
    print("A^-1 =\n", np.linalg.inv(A))
except np.linalg.LinAlgError:
    print("A không khả nghịch")


det(A) = -149.0
A^-1 =
 [[ 0.02684564  0.28187919 -0.26174497]
 [ 0.12751678 -0.16107383  0.00671141]
 [-0.04697987  0.00671141  0.20805369]]
